# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042f5e216b63445157e4f2b92755e751bd156ad0f42936a1ad06e4ab89a595e9a575749a9e2ac2c9c46aa7796291809c3ebe56b17ace5c170b39a62a0aae4764

test:
  secret_key_base: 93dce58d1cd776d7873eea2aaf71d0048a7f2207f073bc7b8fdac928c02edbfbe86e21f8d351085003e58822f75f02d2a35f6d18c5aeb8d2afb1e26e3da0b3ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
